### ISSUE TITLE
Small issue in insol_proc_scr()

### ISSUE THREAD

**Issue by joachim-gassen** [NDelventhal/InsolvencyAnnouncementsGer#1]
Hi Niall:

Great package ;-) We are still building our parsing on it and it works very well so far. I recently came across an issue that you might want to look into. When calling  `insol_proc_scr()` for multiple `reg` values, the page part of the URL is not re-initiated to "1" when looping through `reg`. This causes duplicated scraping of pages and the omission of the first page whenever the prior `reg` value had more than one page.

I fixed it for us by inserting `_u[33] = "1"` after line 202 in `InsolvencyAnnouncementsGer.py`. Thanks for verifying whether I am correct in my interpretation of your code.

Thanks and keep up the good work!

**Comment by NDelventhal** [comment]
Dear Joachim, thanks for this! A fix will be on the way soon. My refactoring of the code didn’t preserve a reinitiating of the page count. Am I right to assume you noticed this on time and the data collection for the TRR 266 has not been affected? The code’s predecessor, we initially have set up on the server, (should have) reset the count correctly. 

Best Regards to Berlin and greetings to the team!

**Comment by joachim-gassen** [comment]
Thanks for the fix. We had the same issue in the server code and it did affect data collection to a limited extend. Glad that it is fixed now. Cheers!
